version: '3.9'
services:
  db:
    image: mariadb:11.0.1-rc-jammy
    container_name: docker-nodejs-mariadb-counter__db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/logs:/var/log/mysql
    ports:
      - "3306:3306"
  app:
    build: ./app
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - "3000:3000"
volumes:
  db-data:
